# Generated by Django 4.2.5 on 2024-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="rede_social",
            field=models.URLField(
                blank=True,
                help_text="Informe o link do Instagram, Facebook, LinkedIn ou outra rede social.",
                max_length=255,
                null=True,
            ),
        ),
    ]
