# Generated by Django 4.2.5 on 2024-03-18 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0002_alter_pessoa_rede_social"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cidade",
            options={"ordering": ["nome", "estado"]},
        ),
    ]
